### ISSUE TITLE
File passed as argument generates "IOError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by juliojsb** [metagriffin/modseclogc#3]
Hello,

It seems modseclogc is not recognizing the file passed as an argument, at least for me:

```
jota@security-audits:~/modsecurity/ModSecurity-log-utilities$ modseclogc --show-request-line --show-parts C modsec.log 
Traceback (most recent call last):
  File "/usr/local/bin/modseclogc", line 11, in <module>
    sys.exit(main())
  File "/home/jota/.local/lib/python2.7/site-packages/modseclogc/cli.py", line 163, in main
    src = source.Source(open(fname, 'rb'), size=None, name=fname)
IOError: [Errno 2] No such file or directory: 'm'
```

```
jota@security-audits:~/modsecurity/ModSecurity-log-utilities$ modseclogc --show-request-line --show-parts C odsec.log 
Traceback (most recent call last):
  File "/usr/local/bin/modseclogc", line 11, in <module>
    sys.exit(main())
  File "/home/jota/.local/lib/python2.7/site-packages/modseclogc/cli.py", line 163, in main
    src = source.Source(open(fname, 'rb'), size=None, name=fname)
IOError: [Errno 2] No such file or directory: 'o'
```

Regards,
Jota

**Comment by miller45** [comment]
@juliojsb open the file $HOME/.local/lib/python2.7/site-packages/modseclogc/cli.py in your editor of your choice and go to line 162. change `option.filename[0]` to `option.filename`.
Then it works and the tool can be quite useful
